version: '2'
services:
    spade:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: spade_server
        restart: always
        command: ./runSpade.sh
        working_dir: /root/spade
        volumes:
          - ./runSpade.sh:/root/spade/runSpade.sh
        ports:
          - ${SPADE_SERVER}:5222
          - ${SPADE_HTTP_SERVER}:8008

    coordinator:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: coordinator_agent
        restart: always
        working_dir: /egr
        volumes:
          - ./emotion-group-recognition:/egr
        command: runCoordinator.sh
        depends_on:
          - spade

    predictor:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: predictor_agent
        restart: always
        working_dir: /egr
        volumes:
          - ./emotion-group-recognition:/egr
        command: runClassificator.sh
        depends_on:
          - spade

    face_recognizer:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: face_recognizer_web
        restart: always
        working_dir: /egr/face_recognizer_server
        volumes:
          - ./emotion-group-recognition:/egr
        command: python web_server.py
        ports:
          - ${FACE_REC_SERVER_PORT}:5001

    web_server:
        image: chverma/node-spade
        container_name: web_server
        restart: always
        working_dir: /webserver
        volumes:
          - ./emotion-webserver:/webserver
        command: bash -c "npm i && ./run.sh"
        ports:
          - ${WEB_SERVER_PORT}:3000
        depends_on:
          - spade
          - predictor
          - coordinator

    nginx:
        image: nginx:1.13
        container_name: nginx_container
        volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${NGINX_PORT}:80"
