version: '2'
services:
    spade:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: spade_server
        restart: always
        command: bash -c "cd /root/spade/ && ./runSpade.sh"
        volumes:
          - ./runSpade.sh:/root/spade/runSpade.sh
        ports:
          # - ${SPADE_SERVER}:5222
          - 8008:8008

    coordinator:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: coordinator_agent
        # restart: always
        volumes:
          - ./emotion-group-recognition:/egr
        command: bash -c "cd /egr/ && ./runCoordinator.sh" #python agentCoordinator.py"
        # depends_on:
        #   - spade
        # links:
        #   - spade

    predictor:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: predictor_agent
        restart: always
        volumes:
          - ./emotion-group-recognition:/egr
        command: bash -c "cd /egr/ && ./runClassificator.sh" #python agentCoordinator.py"
        # depends_on:
        #   - spade
        # links:
        #   - spade

    face_recognizer:
        image: chverma/ubuntu-dlib-pip2-spade
        container_name: face_recognizer_web
        # restart: always
        volumes:
          - ./emotion-group-recognition:/egr
        command: bash -c "cd /egr/face_recognizer_server && python web_server.py" #python agentCoordinator.py"
        ports:
          # - ${SPADE_SERVER}:5222
          - 5001:5001

    # nginx:
    #     image: nginx:1.13
    #     container_name: nginx_container
    #     # volumes:
    #     #     - ./config/default.conf:/etc/nginx/conf.d/default.conf
    #     # ports:
    #     #     - "${NGINX_PORT}:80"
    #     links:
    #         - spade
